name: My first workflow
on: push
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: List and Read files
          run: |
               echo "Hello, there this is my first workflow!"
               ls -ltra
               cat README.md
        - name: Generate ASCII Art
          run: cowsay -f dragon "I am a sassy dragon :p" >> dragon.txt
