name: My first workflow
on: push
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Weclome messgae
          run: echo "Hello, there this is my first workflow!"
        - name: List Files
          run: ls
        - name: Read file
          run: cat README.md