name: Asccii
on: push
jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4
        
        - name: Check repo files
          run: ls -ltra
        
        - name: Executing script
          run: sudo apt install cowsay -y
